# Generated by Django 5.0 on 2024-03-15 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tch_name', models.CharField(max_length=100)),
                ('tch_email', models.CharField(max_length=100)),
                ('tch_contact', models.IntegerField(null=True)),
                ('DOB', models.DateField(null=True)),
            ],
        ),
    ]
